spring:
    thymeleaf:
        cache: false

png:
    sso:
        appid: shrgiven
        appkey: xxxxshrgiven123
        uri: http://10.100.113.69:8080/sso-inf/
    sms:
        tencent:
            appkey: xxxxx28ef64adf566c2af0dc207657395d8cb
            appid: 1400328541
            smsSign: "铂涛集团"
            templateId: 550257
